# .air.toml
# This file configures 'air' to ignore specific directories
# and optimize its watching behavior.

[build]
# Command to build your Go application.
# Default: go build -o <tmpdir>/main .
cmd = "go build -o ./tmp/main.exe ." # Using ./tmp for the build output with .exe extension for Windows

# Binary name.
# bin = "tmp/main" # This assumes 'tmp' directory in your project root
bin = "./tmp/main.exe"

# Path to watch for file changes.
# Default: . (current directory)
include_dir = [
    ".", # Watch the current directory
]

# Files to include even if their directory is ignored.
include_ext = ["go"]

# Exclude these types of files.
# exclude_ext = ["go", "md"]

# Delay for file change detection in milliseconds.
delay = 1000

# Run 'air' in verbose mode.
# Default: false
verbose = true

[log]
# Log level for air.
# Options: trace, debug, info, warn, error, fatal
level = "info"

[server]
# Command to run after build.
# Default: <bin>
cmd = "./tmp/main.exe"

# Port for the server.
port = 8083

# Paths to ignore for file changes.
ignore_dir = [
    "tmp", # Ignore the temporary build directory
    "vendor", # If you use Go modules vendor directory
    "node_modules", # If you have any frontend setup
    ".git", # Ignore git directory
    ".vscode", # Ignore VS Code settings
    "WORKSPACE2", # Ignore other workspace
]

# Directories to exclude from watching.
exclude_dir = ["static", "templates", "tmp", ".git", ".vscode", "WORKSPACE2"]
