# .air.toml
# Configuración optimizada para hot reloading

[build]
# Comando para compilar tu aplicación Go
cmd = "go build -o ./tmp/main.exe ."

# Nombre del binario
bin = "./tmp/main.exe"

# Directorios a incluir en el watching
include_dir = ["."]

# Extensiones de archivo a vigilar
include_ext = ["go", "html", "css", "js", "json"]

# Delay para detección de cambios (en milisegundos)
delay = 500

# Directorio temporal para builds
tmp_dir = "tmp"

# Directorios a excluir del watching
exclude_dir = [
    "tmp", 
    "vendor", 
    "node_modules", 
    ".git", 
    ".vscode", 
    "WORKSPACE2"
]

# Archivos a excluir
exclude_regex = ["_test\\.go"]

# Log de errores de build
log = "tmp/build-errors.log"

# Limpiar pantalla en cada rebuild
[screen]
clear_on_rebuild = true

[log]
# Mostrar solo logs principales
main_only = false
time = true

[color]
# Colores para la salida
app = "blue"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"
