# .air.toml
# This file configures 'air' to ignore specific directories
# and optimize its watching behavior.

[build]
# Command to build your Go application.
# Default: go build -o <tmpdir>/main .
cmd = "go build -o ./tmp/main ." # Using ./tmp for the build output with .exe extension for Windows

# Binary name.
# bin = "tmp/main" # This assumes 'tmp' directory in your project root
bin = "./tmp/main"

# Path to watch for file changes.
# Default: . (current directory)
include_dir = [
    ".", # Watch the current directory
]

# Files to include even if their directory is ignored.
include_ext = ["go"]

# Exclude these types of files.
# exclude_ext = ["go", "md"]

# Delay for file change detection in milliseconds.
delay = 1000

# Run 'air' in verbose mode.
# Default: false
# verbose = true

[log]
# Log level for air.
# Options: trace, debug, info, warn, error, fatal
level = "info"

[server]
# Command to run after build.
# Default: <bin>
cmd = "./tmp/main"

# Port for the server.
port = 8080

# Paths to ignore for file changes.
# This is where we'll add the BraveSoftware path.
ignore_dir = [
    "tmp", # Ignore the temporary build directory
    "vendor", # If you use Go modules vendor directory
    "node_modules", # If you have any frontend setup
    # Add the problematic BraveSoftware path here, using the absolute path
    "/Users/libertarian.one/Library/Application Support/BraveSoftware",
    # You can add other 'Library/Application Support' subdirectories here if you keep seeing "failed to watch" errors
    # "/Users/libertarian.one/Library/Application Support/Adobe",
    # "/Users/libertarian.one/Library/Application Support/Bitcoin",
]

# Directories to exclude from watching.
exclude_dir = ["static", "templates", "tmp"]
